### ISSUE TITLE
MAP Stub enhancement for MAP SRIforLCS, MAP PSL and MAP SLR operations (LSM) support.

### ISSUE THREAD

**Issue by deruelle** [RestComm/gmlc#1]
MAP SRIforLCS, MAP PSL and MAP SLR support in GMLC for 3G location services.

**Comment by FerUy** [comment]
LSM (Location Services Management) operations, i.e. MAP SRIforLCS, MAP PSL and MAP SLR support in GMLC (Lg + Lh interfaces to MSCS or SGSN and HSS respectively) for Location Services support in Circuit-Switched Core Networks were a Stand-Alone SMLC (Serving Mobile Location Centre) is located (mostly 3G Radio Access Networks like UMTS Terrestrial RAN).

As confirmed by @abhayani , locationSvcGatewayContext and locationSvcEnquiryContext Application Context Name operations including MAP SRIforLCS, MAP PSL and MAP SLR (Subscriber Location Report), are already implemented. Hence, Lg + Lh interfaces to MSCS and HSS respectively would be available for embed in current GMLC implementation.

Likewise, an upgrade of jSS7 simulator to include these operations would be needed (only MAP ATI is included today for GMLC location services simulation), and posterior testing so as to consider this issue as solved and milestone accomplished. That upgrade is being covered by https://github.com/RestComm/jss7/issues/100

The diagram below displays a signal flow diagram of GMLC processing all of these operations (only one Location Report from the network is shown for simplicity).
![gmlc_signal_flow_umts](https://cloud.githubusercontent.com/assets/14883482/18225655/13ef366c-71ce-11e6-9cf9-37f0c7d05fb9.png)

**Comment by FerUy** [comment]
@jarmex any feedback from your side?
Should I assign anybody else?

**Comment by angrygreenfrogs** [comment]
@FerUy Related to this - can you help us with understanding how 2g/3g/4g location tie together with the MAP ATI operation?

So we have access to our test MNO at the moment where we're able to send MAP ATI requests into their system (to their MSC I believe)

This is what we've been discussing as being a "2g location", right? So is it expected this call/process still works for a device that is actually connected to the network via 3g/4g?

We're curious because basically our test MNO MAP ATI requests are working fine, but we believe the target MSISDN we're locating is actually connected via 4G to the network, so we're just surprised that it works basically and want to understand how/if that's expected.

Similar question about roaming... with just the map request we have implemented now, would it still be expected we get a result back if the device is roaming?

**Comment by FerUy** [comment]
Yes, MAP ATI can be considered as 2G location (defined from CAMEL phase II -please don't confuse, CAMEL includes not only CAP, but also MAP operations like ATI-). You're not sending the request to the MSC but the HLR/HSS (HSS is HLR evolution from 3G onwards).

It doesn't matter if the device is connected to 3G/4G, MAP ATI would still work as the HLR or HSS will always have the location information requested from that operation stored. Have in mind that this information is always according to the latest MAP UL between the HLR and VLR at which the target subscriber is attached to (hence, the information could be obsolete, that's when the Age of Location information parameter -in minutes- takes importance-).

Also, user equipment attached to LTE (all-IP Packet-Switched network), still perform in most cases for many operations including voice, USSD, SMS, etc., what is called CSFB (Circuit-Switched Fall Back), so don't worry about using MAP ATI for subscribers attached to LTE E-UTRAN, it will still work. Even if they roam to non-LTE access, Evolved Packet Core (EPC) entities anchors it to the Packet-Switched Network.

Regarding roaming, good question. It will work too if the subscriber is roaming in a V-PLMN (Visited Public Land Mobile Network) that has an agreement with H-PLMN (Home PLMN). As you're requesting the response from the H-PLMN HLR, the latter will have the location information at the V-PLMN. When the user attaches to a VLR at the V-PLMN, CAMEL Subscription Information is exchanged with the H-PLMN (to acknowledge which services are available for the roamer), and location information is periodically updated between network nodes (VLRs and H-PLMN HLR). I tested this myself back in 2005 and it works (I issued a MAP ATI for my Guatemalan MSISDN -to the Guatemalan HLR- while roaming in El Salvador, and the GCI retrieved was exactly from where I was roaming in El Salvador). Same concept as with USSD (as the HLR is the relay entity), when you dial a USSD short code while roaming, the V-PLMN redirects you to your H-PLMN HLR (and it does the same to the USSD Gateway or Service Control Point that controls that short code). It all works as long as the V-PLMN and the H-PLMN (the involved MNOs) have an agreement and don't bar this (which usually never happens).

Hope it answers all your doubts about it.

**Comment by angrygreenfrogs** [comment]
Thank you @FerUy as usual a great response, I'm saving that one. Yep, that answers absolutely everything.

**Comment by FerUy** [comment]
Solved with PR #96
