### ISSUE TITLE
Adding info into response for mcc, mnc, lac as an addition to cellid

### ISSUE THREAD

**Issue by vetss** [RestComm/gmlc#13]
1) In GET HTTP methid we send in response only "cellid=xxx" response. We need to respond also mcc,mnc,lac and may respond in the followinf format:
mcc=aaa,mnc=bbb,lac=ccc,cellid=xxx

Values can be taken from CellGlobalIdOrServiceAreaIdFixedLength:
    int getMCC() throws MAPException;
    int getMNC() throws MAPException;
    int getLac() throws MAPException;
    int getCellIdOrServiceAreaCode() throws MAPException; (we use it)
**Important**: we need to check if "CellGlobalIdOrServiceAreaIdFixedLength" is null or not

2) for POST HTTP we do not respond now cellid value (and mcc,mcc,lac) at all. We need to think how can we respond it in DTD set:
cellid,mcc,mcc,lac filelds are inckluded in the class:
org.oma.protocols.mlp.svc_result.Cgi
Cgi is included in GsmNetParam class, GsmNetParam is included Pos class.
But "Pos" class is uncluded in several classes that are included in SvcResult. We need to understand the proper class usage.

**Comment by deruelle** [comment]
@angrygreenfrogs can you comment on the impact of this issue on MLP ? Would you potentially be willing to help on fixing the MLP part if needed to expose those additional info ?

**Comment by angrygreenfrogs** [comment]
@deruelle No worries, I'll certainly help if I can.

@vetss Looks to be on the right track, and we'll frankly just have to give it a shot and see if there's any issues.

[MLP_GSM_NET_310.xsd.txt](https://github.com/RestComm/gmlc/files/159820/MLP_GSM_NET_310.xsd.txt)

MLP_GSM_NET_310.DTD defines gsm_net_param, which is indeed present in the pos element of the svc_result

We should be able to generate a XML result like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svc_result SYSTEM "MLP_SVC_RESULT_310.DTD">
<svc_result xmlns="MLP_SVC_RESULT_310.dtd" ver="3.1.0">
    <slia ver="3.1.0">
        <pos>
            <msid>MSISDN OF TARGET</msid>
            <pd>
                <time utc_off="-0700">20150314141702</time>
            </pd>
            <gsm_net_param>
              <cgi>
                  <mcc>1</mcc>
                  <mnc>829</mnc>
                  <lac>3069998</lac>
                  <cellid>3333</cellid>
              </cgi>
            </gsm_net_param>
        </pos>
    </slia>
</svc_result>
```
