### ISSUE TITLE
Processing of MAP errors / rejects

### ISSUE THREAD

**Issue by vetss** [RestComm/gmlc#15]
We need to add of processing of MAP errors / rejects and return proper info for this into HTTP responses.

**Comment by deruelle** [comment]
We are evaluating which option is best:
1. reply with a custom HTTP Response code
2. Do it like for CAMEL GW
3. Do it like USSD GW

**Comment by dsendind** [comment]
If I see it from a product experience perspective, I think that providing a map from typical MAP to HTTP such as "Absent Subscriber", "Unknown" or other type could enrich the experience.  I am sure that this will be demanded somehow sooner or later..

**Comment by nhanth87** [comment]
Some comment from me:
Most of error code will return in onErrorComponent()
  public void onErrorComponent(ErrorComponent event, ActivityContextInterface aci)
  {
    MAPErrorMessage mapErrorMessage = event.getMAPErrorMessage();
    long error_code = mapErrorMessage.getErrorCode().longValue();

```
continueHttpError(error_code, true);
```

  }

**Comment by vetss** [comment]
Tran, as for your last comment:
- some error messages contains also extra parameters on board
- we need to care along with onErrorComponent() to other error cases (providerd / user aborts, dialog and invoke rejects, dialog and invoke timeouts, etc)

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/gmlc/commit/e14a3c04765650055b8d7efdb30680d8d28aea2c

**Comment by vetss** [comment]
Extra fix:

https://github.com/RestComm/gmlc/commit/93798c18e64531ae75f45573e250bf2c11d522cd
