### ISSUE TITLE
Automated Performance test CI job for GMLC

### ISSUE THREAD

**Issue by vetss** [RestComm/gmlc#23]
We need to create an automated perf test for testing of GMLC.

**Comment by deruelle** [comment]
Integrate it with PerfCorder

**Comment by jaimecasero** [comment]
CI job to be completed

**Comment by FerUy** [comment]
Most of the CI job skeleton is working. @jaimecasero is updating CI job image to include zip tool so PerfCorder may record collection properly. 
Then @Feruy needs to work on launching GMLC and configuring, and later work on proper MAP stub to receive traffic on southbound interface.

**Comment by jaimecasero** [comment]
@FerUy  Im handing over this to you. The script at https://bitbucket.org/telestax/telscale-commons/src/42f99f527e0cabdd101a2fedb21b7c63687c5556/jenkins-aws/Jenkins-Jobs/GMLC/GMLC-Performance-GetLoc_EC2.sh?at=master&fileviewer=file-view-default where the CI job commands are located. Now both Perfcorder, and jmeter are working against a preliminar GMLC process. Is your turn to properly set the process ( in terms of JAVA_OPTS), and complete the testing environment with MAP stub as we discussed...

**Comment by FerUy** [comment]
Just for the record, adding client and server console outputs of a test. Responses are just like expected/coded.
[Server_console_20160831.txt](https://github.com/RestComm/gmlc/files/448500/Server_console_20160831.txt)
[Client_console_20160831.txt](https://github.com/RestComm/gmlc/files/448501/Client_console_20160831.txt)

**Comment by jaimecasero** [comment]
great @FerUy  time to start that server from performance script and let the traffic complete into the server (we may need to change the JMeter test plan to prevent the fake isdn)

**Comment by FerUy** [comment]
Noted, thanks @jaimecasero

**Comment by FerUy** [comment]
Regarding last commit, find attached console log when running client and server in the same run instance.
[ClientServer_console_log.txt](https://github.com/RestComm/gmlc/files/459564/ClientServer_console_log.txt)
