### ISSUE TITLE
GMLC configuration is broken

### ISSUE THREAD

**Issue by Vanit** [RestComm/gmlc#28]
I'm not sure what the expected result is or if configuration services are in fact supposed to be here, but this is the current output.

<img width="1007" alt="screen shot 2016-06-17 at 2 21 56 pm" src="https://cloud.githubusercontent.com/assets/852857/16140723/09532d90-3497-11e6-94f2-9ef5655c9550.png">

**Comment by nhanth87** [comment]
some problem with jss7 management console and in investigating, but it will not affect the system

**Comment by nhanth87** [comment]
Hi,
this issue related to jss7 management console, not gmlc.
I created ticket for it 
https://github.com/RestComm/jss7/issues/136

So I closed this ticket now

Br,
TN
