### ISSUE TITLE
Re-factor the directory structure and maven build files to more closely match the SMS gateway

### ISSUE THREAD

**Issue by angrygreenfrogs** [RestComm/gmlc#34]
In addition to upgrading JSS7 (https://github.com/RestComm/jss7/issues/61) and other related issues, Fernando indicated that the SMS gateway is the best example of how the project should be structured and built.

To that end, I'm working on a restructured branch with updated pom files that more closely matches the SMS gateway structure.

**Comment by FerUy** [comment]
Hi Andrew, already started this, take a look to https://github.com/RestComm/gmlc/commit/a75b4f3df65e69e881d5530a971a32731e84551f in first_build branch

**Comment by angrygreenfrogs** [comment]
This is now covered in the pull request here: https://github.com/RestComm/gmlc/pull/37

I'm assuming we'll pull all changes into the first_build branch, and Fernando and I can keep working there until the new build is ready
