### ISSUE TITLE
HTTP servlet dependency not being installed with release/build.xml

### ISSUE THREAD

**Issue by angrygreenfrogs** [RestComm/gmlc#42]
The build is missing the equivalent of this resource:

cd ~/RestComm/resources/http-servlet
ant deploy

It's contained inside of "restcomm-slee-2.8.36.73.zip", which we're already downloading, so I think we just need to find a nice way to have it automatically added to the right target in build.xml

**Comment by angrygreenfrogs** [comment]
@FerUy @vetss Let me know please if you guys have any pointers on the best practice way of doing this, but otherwise I think I can piece it together from similar bits in the build

**Comment by deruelle** [comment]
@angrygreenfrogs you may want to check the USSD Gateway build has it has the HTTP Servlet RA. Can't recall if it is deployed by default out of the box but I think it is.

**Comment by angrygreenfrogs** [comment]
I followed Jean's advice, and used the same method as the USSD gateway does in its build. I modified it a little bit to handle an error with running the build script twice, but it's working just fine now.

Fixed in this commit https://github.com/RestComm/gmlc/commit/ea541869d99d7ff8fd3a0272fa8d8a8e9ec4c258
