### ISSUE TITLE
update to 2.1.0 ss7

### ISSUE THREAD

**Issue by ibstelix** [RestComm/gmlc#5]
Update to 2.1.0 ss7
Gist for the patch: https://gist.github.com/ibstelix/3f2fc8bf879dd16db1c7

**Comment by deruelle** [comment]
Can you please attach the git patch and sign the Contributor License Agreement at http://www.telestax.com/open-source-2/#Contribute ?

**Comment by deruelle** [comment]
The patch doesn't seem to match the commit https://github.com/ibstelix/gmlc/commit/4adcd50330eabe26a3679f5de43394b221d3451f?diff=split, your patch covers all the files of the project for some reason. Can you try to generate a better patch file ?

**Comment by ibstelix** [comment]
Hi, i re-created the patch : https://gist.github.com/ibstelix/b145526c0cc6e40c98a9

**Comment by deruelle** [comment]
It would be better to move to latest version from https://mobicents.ci.cloudbees.com/job/Mobicents-jSS7/ ie 3.0.1316.

**Comment by deruelle** [comment]
Merged and upgraded to latest version

**Comment by deruelle** [comment]
Thanks @ibstelix , acknowledged at http://www.telestax.com/open-source/acknowledgments/
