### ISSUE TITLE
Route requests to protocol specific methods in MobileCoreNetworkInterfaceSbb

### ISSUE THREAD

**Issue by Vanit** [RestComm/gmlc#50]
Currently https://github.com/RestComm/gmlc/blob/master/core/slee/services/sbbs/src/main/java/org/mobicents/gmlc/slee/MobileCoreNetworkInterfaceSbb.java responds to all request URIs and handles protocols based on the request type (GET -> rest, POST -> mlp). Ideally there should a different URI per protocol that's mapped to its own method, ie:
- /restcomm/gmlc/rest -> void rest(params)
- /restcomm/gmlc/mlp -> void mlp(params)
- /restcomm/gmlc/sip -> void sip(params)
- else -> void 404(params)

It should be noted that the /restcomm part of the URI is determined by the http-servlet and the code should just work if it's changed.

As we just need to do simple URI -> method routing I'd suggest writing a small class (or even method) to handle it.

**Comment by Vanit** [comment]
Assign to me please :)

**Comment by FerUy** [comment]
All yours ;)

**Comment by FerUy** [comment]
@Monix any update from your side on this?

**Comment by Vanit** [comment]
@FerUy I've been swamped at work for the last week so no progress, but I'm about to free up so should have something either today or tomorrow :)

**Comment by FerUy** [comment]
Great!
Thanks for the quick update @Monix :+1:

**Comment by FerUy** [comment]
Hi @Monix, I will do it soon after some testing with the latest build.
