### ISSUE TITLE
Issue testing OPEN GMLC simulator

### ISSUE THREAD

**Issue by johnnyAnd** [RestComm/gmlc#51]
I was testing the GMLC simulator by following[ this link ](http://documentation.telestax.com/core/gmlc/GMLC_Admin_Guide.html#_gmlc_overview)and doing pull request.

Unfortunately there is a place where it asks to dial *519# to get response from server, but there is no place for that..

![capture](https://cloud.githubusercontent.com/assets/15995036/16906976/962b4a46-4cd8-11e6-8c7e-3342dceb5e00.PNG)

This is screen that I get [which is supposed to be this.](http://documentation.telestax.com/core/ussd/images/USSD_SS7_Simulator_Process_Unst_request.png)

Allowing message text .

**Comment by FerUy** [comment]
@JohnTet GMLC is under construction at this moment for its first official release (v1.0.0). For now, please stick with the README instructions [here](https://github.com/RestComm/gmlc).
Stay tuned at Restcomm Google public group or [Restcomm public forum](https://gitter.im/RestComm/Restcomm-discuss) as it will be released soon, in a matter of the next few weeks, with proper updated documentation.

*519# is not under GMLC concern, that's a USSD short code, it will never be directed to a GMLC but to a USSD Gateway (although a USSD Gateway could, and specifically our USSD Gateway, will trigger Location Based Services via the GMLC through RestComm-Connect). So, dialing *519# with the jSS7 simulator has nothing to do with GMLC but with USSD Gateway (an issue regarding this matter should be placed [here ](https://github.com/RestComm/ussdgateway) instead). 

For all of what's been said, I'm closing this issue right now.

**Comment by johnnyAnd** [comment]
@FerUy so one cannot test GMLC location testing on localhost ?

**Comment by FerUy** [comment]
@JohnTet yes you can, please see follow the instructions of README [here](github.com/RestComm/gmlc).

**Comment by johnnyAnd** [comment]
@FerUy that is 404, I have gone through the git instructions though. I have created another issue since this one is closed.
