### ISSUE TITLE
Document the basics of the system and code architecture

### ISSUE THREAD

**Issue by angrygreenfrogs** [RestComm/gmlc#59]
One thing that makes the project hard to enter as a new contributor is a lack of understanding of the underlying system and architecture.

It's a bit onerous when you see the number of dependencies and inter-connecting bits outputting 1000 messages when you start up JBoss and watch the console output.

It'd be great to include a basic explanation of the components involved, links to docs to read up on, and an explanation of the code structure. JAIN SLEE, how the HTTP RA fits in, what a SBB is.... other things?

https://docs.jboss.org/mobicents/jain-slee/2.7.0.FINAL/container/user-guide/en-US/html/introduction.html

I noticed there's actually a better short wikipedia article in Spanish than in English on the subject =)

https://es.wikipedia.org/wiki/JSLEE#Service_Building_Block_.28SBB.29

I'm new here myself, so I'm not really clear on all of this and how to write an intro, so hoping to ask for help from the experts?

**Comment by FerUy** [comment]
I couldn't agree more @angrygreenfrogs 
Thanks for opening this issue and bringing this up.
