### ISSUE TITLE
add requested service

### ISSUE THREAD

**Issue by loayking** [RestComm/gmlc#79]
Hi @all, I think we need to add requested service parameter as follow
http://127.0.0.1:8080/restcomm/gmlc/rest?msisdn=87583439&requested=*888#
this will help later in CDR

**Comment by loayking** [comment]
Hello @FerUy , please check the changes @ https://github.com/RestComm/gmlc/compare/master...loayking:Me?expand=1

I select URL parameter name serviceid instead of requested,
and i supposed the tag <serviceid> in MLP request is for the same .
if it is ok i will make pull request

**Comment by FerUy** [comment]
Thanks @loayking, please proceed with the PR. It will be merged for milestone 2.0.0, after we complete issue #23 which will hopefully happen next Monday.

**Comment by loayking** [comment]
done @FerUy

**Comment by FerUy** [comment]
Thanks!

**Comment by FerUy** [comment]
Closed by https://github.com/RestComm/gmlc/pull/81
