### ISSUE TITLE
Make GMLC execution of MAP SRIforLCS, PSL and SLR configurable

### ISSUE THREAD

**Issue by FerUy** [RestComm/gmlc#92]
By putting a flag in a configuration file, MAP operations destined to retrieve real time location information from the RAN (through a Stand-Alone SMLC) will be executed after MAP ATI is performed. Through this way, MAP ATI will provide last known location information in terms of Global Cell Identification, while MAP SRIforLCS, MAP PSL and MAP SLR will eventually provide real-time and more accurate location information and event reports.

**Comment by moehi** [comment]
Hi,

Any Update ?

Already succes integration with ATI over STP
And need to request with SRI and PSL over STP

thanking in advance

**Comment by FerUy** [comment]
Hi @moehi, same answer as in [issue 91](https://github.com/RestComm/gmlc/issues/91).
