### ISSUE TITLE
gmlc over sctp issue

### ISSUE THREAD

**Issue by zidanekeren** [RestComm/gmlc#98]
hi guys.

first of all, i'm completely new with this.
so please help/guide me so i can solved this issue.

i'm in the middle of implementing new gmlc over sctp.
the sctp connection seems correct, because the status are up.
and im doing some testing using ati command, 
by pcap i can see the result there, but at web app it doesnt show anything..

can you guys please share with me how to solve this issue.

thanks.

**Comment by zidanekeren** [comment]
updated.
i've misconfigured with address. now i can see result with ati command.
now i have another problem. i cant see the phone status. 
do you guys have any idea where should i seek the problem is? 

thanks.

**Comment by FerUy** [comment]
Hi @zidanekeren,

The "problem" is that GMLC (Gateway Mobile **Location** Center) main concern is, well, location, so there's no code dedicated to provide status (*idle*, *camel_busy*, etc.), although MAP ATI retrieves it. It's not an error, but which has been thought should be part of GMLC scope thus far, i.e. only location of the mobile subscriber.

Again, this is not an issue, then please post this kind of questions in Restcomm Google group https://groups.google.com/forum/#!forum/restcomm thru email or in https://gitter.im/RestComm/gmlc. If you believe this is a feature that should be included in Restcomm GMLC, then please use https://github.com/RestComm/gmlc and open a new issue with titled like "Include subscriber status in MAP ATI response", and we will treat it as such and decide if needs to be included in the roadmap or not.

Thanks!
